name: places
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  drift: ^2.4.2
  elementary: ^2.0.0
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_image_compress: ^1.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  http_parser: ^4.0.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  map_launcher: ^2.5.0+1
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  retrofit: ^3.3.1
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.12
  yandex_mapkit: ^3.2.0

dev_dependencies:
  build_runner: ^2.3.2
  dart_code_metrics: ^5.0.1
  drift_dev: ^2.4.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0

flutter_icons:
  image_path: 'assets/icons/dev_app_icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
