/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const IconData arrow_back = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_left = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_right = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_up = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bucket = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_full = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_1 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fail = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData go = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData go_1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotel = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_heart = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_heart_full = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_list = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_list_full = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_map = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_map_full = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_settings = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_settings_fill = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData museum = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData park = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData particular_place = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restourant = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spash_screen_logo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tutorial_bag = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tutorial_click = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tutorial_signs = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;
}
